# Generated by Django 6.0.2 on 2026-02-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['id'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='unique_avaliacao',
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('email', 'curso')},
        ),
    ]
